apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: todo-app-db-credentials
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: todo-app-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: db-host
      remoteRef:
        key: {{ .Values.externalSecrets.parameterPrefix }}/db-host
    - secretKey: db-port
      remoteRef:
        key: {{ .Values.externalSecrets.parameterPrefix }}/db-port
    - secretKey: db-name
      remoteRef:
        key: {{ .Values.externalSecrets.parameterPrefix }}/db-name
    - secretKey: db-user
      remoteRef:
        key: {{ .Values.externalSecrets.parameterPrefix }}/db-user
    - secretKey: db-password
      remoteRef:
        key: {{ .Values.externalSecrets.parameterPrefix }}/db-password
